services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: penguin
      MYSQL_DATABASE: RetroGameDatabase
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - distributed-network


  api:
    build:
      context: ./api
    environment:
      SQL_ROOT: root
      SQL_PASSWORD: penguin
      SQL_PORT: 3306
      DB_HOST: gameapi-db-1
      DATABASE: RetroGameDatabase
      API_HOST: 8080
    depends_on:
      - db
    deploy:
      replicas: 3
    networks:
     - distributed-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - distributed-network

volumes:
  dbdata:

networks:
  distributed-network:
    name: distributed-network

